title: VRG docs
description: An unofficial VRG documentation
theme: just-the-docs

url: https://klarajanouskova.github.io/VRG

defaults:
  -
    scope:
      path: "docs" # Applies to all files
    values:
      layout: "default"